version: '3.7'

services:
  redis:
    image: redis:6.0.5
    container_name: redis
    hostname: redis6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    command: redis-server

  postgresql:
    image: postgres:latest
    container_name: postgres
    hostname: postgres5432
    labels:
      - "name=postgresql"
    ports:
      - 10003:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: B2B-DB
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
